### ISSUE TITLE
Can't find crate for glass.

### ISSUE THREAD

**Issue by yelzgniq** [C-Bouthoorn/rust-glass#1]
Hey, i'm a newbie in rust, so forgive me if this is a silly issue.
I tried running the main.rs file with rustc command and it returned 

```
error[E0463]: can't find crate for 'glass'
 --> main.rs:1:1
  |
1 | extern crate glass;
  | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

Thanks.

**Comment by Cxarli** [comment]
Hey! First of all, everyone started as a "newbie", so there's no need to ask for forgiveness :blush: 

~Second: Indeed, and that's my fault. Give me a second and I'll fix it for you~

Should be fixed in https://github.com/C-Bouthoorn/rust-glass/commit/2c9117a5b691036dde0283665232b8ec2ed34a99. The crate can be found at https://crates.io/crates/glass

To use it in your project, you'll have to add `glass = "0.1.0"` under `[dependencies]` to your `Cargo.toml` file.
It should all be explained in [this guide](http://doc.crates.io/guide.html)

**Comment by yelzgniq** [comment]
Thanks.
